#ifndef BIOME_H_
#define BIOME_H_

#define BIOME_OCEAN 0
#define BIOME_PLAINS 1
#define BIOME_DESERT 2
#define BIOME_EXTREME_HILLS 3
#define BIOME_FOREST 4
#define BIOME_TAIGA 5
#define BIOME_SWAMPLAND 6
#define BIOME_RIVER 7
#define BIOME_HELL 8
#define BIOME_THE_END 9
#define BIOME_FROZENOCEAN 10
#define BIOME_FROZENRIVER 11
#define BIOME_ICE_PLAINS 12
#define BIOME_ICE_MOUNTAINS 13
#define BIOME_MUSHROOMISLAND 14
#define BIOME_MUSHROOMISLANDSHORE 15
#define BIOME_BEACH 16
#define BIOME_DESERTHILLS 17
#define BIOME_FORESTHILLS 18
#define BIOME_TAIGAHILLS 19
#define BIOME_EXTREME_HILLS_EDGE 20
#define BIOME_JUNGLE 21
#define BIOME_JUNGLEHILLS 22
#define BIOME_JUNGLEEDGE 23
#define BIOME_DEEP_OCEAN 24
#define BIOME_STONE_BEACH 25
#define BIOME_COLD_BEACH 26
#define BIOME_BIRCH_FOREST 27
#define BIOME_BIRCH_FOREST_HILLS 28
#define BIOME_ROOFED_FOREST 29
#define BIOME_COLD_TAIGA 30
#define BIOME_COLD_TAIGA_HILLS 31
#define BIOME_MEGA_TAIGA 32
#define BIOME_MEGA_TAIGA_HILLS 33
#define BIOME_EXTREME_HILLS_PLUS 34
#define BIOME_SAVANNA 35
#define BIOME_SAVANNA_PLATEAU 36
#define BIOME_MESA 37
#define BIOME_MESA_PLATEAU_F 38
#define BIOME_MESA_PLATEAU 39
#define BIOME_THE_VOID 127
#define BIOME_SUNFLOWER_PLAINS 129
#define BIOME_DESERT_M 130
#define BIOME_EXTREME_HILLS_M 131
#define BIOME_FLOWER_FOREST 132
#define BIOME_TAIGA_M 133
#define BIOME_SWAMPLAND_M 134
#define BIOME_ICE_PLAINS_SPIKES 140
#define BIOME_JUNGLE_M 149
#define BIOME_JUNGLE_EDGE_M 151
#define BIOME_BIRCH_FOREST_M 155
#define BIOME_BIRCH_FOREST_HILLS_M 156
#define BIOME_ROOFED_FOREST_M 157
#define BIOME_COLD_TAIGA_M 158
#define BIOME_MEGA_SPRUCE_TAIGA 160
#define BIOME_REDWOOD_TAIGA_HILLS_M 161
#define BIOME_EXTREME_HILLS_PLUS M 162
#define BIOME_SAVANNA_M 163
#define BIOME_SAVANNA_PLATEAU_M 164
#define BIOME_MESA_BRYCE 165
#define BIOME_MESA_PLATEAU_F M 166
#define BIOME_MESA_PLATEAU_M 167

#endif /* BIOME_H_ */
