/*
 * block.c
 *
 *  Created on: Dec 24, 2016
 *      Author: root
 */

#include "block.h"
#include "util.h"
#include "inventory.h"
#include "game.h"
#include "world.h"
#include "xstring.h"
#include "queue.h"
#include "smelting.h"
#include "tileentity.h"
#include "smelting.h"
#include "network.h"

struct block_info block_infos[BLOCK_LIMIT];

void onBlockInteract_workbench(struct world* world, block blk, int32_t x, int32_t y, int32_t z, struct player* player, uint8_t face, float curPosX, float curPosY, float curPosZ) {
	struct inventory* wb = xmalloc(sizeof(struct inventory));
	newInventory(wb, INVTYPE_WORKBENCH, 1, 10);
	wb->title = xstrdup("{\"text\": \"Crafting Table\"}", 0);
	player_openInventory(player, wb);
}

void onBlockDestroyed_chest(struct world* world, block blk, int32_t x, int32_t y, int32_t z) {
	//TODO: spill items
	setTileEntityWorld(world, x, y, z, NULL);
}

void onBlockInteract_chest(struct world* world, block blk, int32_t x, int32_t y, int32_t z, struct player* player, uint8_t face, float curPosX, float curPosY, float curPosZ) {
	struct tile_entity* te = getTileEntityWorld(world, x, y, z);
	if (te == NULL || !streq_nocase(te->id, "minecraft:chest")) {
		te = newTileEntity("minecraft:chest", x, y, z);
		te->data.chest.lock = NULL;
		te->data.chest.inv = xmalloc(sizeof(struct inventory));
		newInventory(te->data.chest.inv, INVTYPE_CHEST, 2, 27);
		te->data.chest.inv->te = te;
		te->data.chest.inv->title = xstrdup("{\"text\": \"Chest\"}", 0);
		setTileEntityWorld(world, x, y, z, te);
	}
	//TODO: impl locks, loot
	player_openInventory(player, te->data.chest.inv);
	BEGIN_BROADCAST_DIST(player->entity, 128.)
	struct packet* pkt = xmalloc(sizeof(struct packet));
	pkt->id = PKT_PLAY_CLIENT_BLOCKACTION;
	pkt->data.play_client.blockaction.location.x = x;
	pkt->data.play_client.blockaction.location.y = y;
	pkt->data.play_client.blockaction.location.z = z;
	pkt->data.play_client.blockaction.action_id = 1;
	pkt->data.play_client.blockaction.action_param = te->data.chest.inv->players->count;
	pkt->data.play_client.blockaction.block_type = blk >> 4;
	add_queue(bc_player->outgoingPacket, pkt);
	flush_outgoing (bc_player);
	END_BROADCAST
}

void onBlockDestroyed_furnace(struct world* world, block blk, int32_t x, int32_t y, int32_t z) {
	//TODO: spill items
	setTileEntityWorld(world, x, y, z, NULL);
}

void onBlockInteract_furnace(struct world* world, block blk, int32_t x, int32_t y, int32_t z, struct player* player, uint8_t face, float curPosX, float curPosY, float curPosZ) {
	struct tile_entity* te = getTileEntityWorld(world, x, y, z);
	if (te == NULL || !streq_nocase(te->id, "minecraft:furnace")) {
		te = newTileEntity("minecraft:furnace", x, y, z);
		te->data.furnace.lock = NULL;
		te->data.furnace.inv = xmalloc(sizeof(struct inventory));
		newInventory(te->data.furnace.inv, INVTYPE_FURNACE, 3, 3);
		te->data.furnace.inv->te = te;
		te->data.furnace.inv->title = xstrdup("{\"text\": \"Furnace\"}", 0);
		setTileEntityWorld(world, x, y, z, te);
	}
	//TODO: impl locks, loot
	player_openInventory(player, te->data.furnace.inv);
	struct packet* pkt = xmalloc(sizeof(struct packet));
	pkt->id = PKT_PLAY_CLIENT_WINDOWPROPERTY;
	pkt->data.play_client.windowproperty.window_id = te->data.furnace.inv->windowID;
	pkt->data.play_client.windowproperty.property = 1;
	pkt->data.play_client.windowproperty.value = te->data.furnace.lastBurnMax;
	add_queue(player->outgoingPacket, pkt);
	flush_outgoing(player);
	pkt = xmalloc(sizeof(struct packet));
	pkt->id = PKT_PLAY_CLIENT_WINDOWPROPERTY;
	pkt->data.play_client.windowproperty.window_id = te->data.furnace.inv->windowID;
	pkt->data.play_client.windowproperty.property = 3;
	pkt->data.play_client.windowproperty.value = 200;
	add_queue(player->outgoingPacket, pkt);
	flush_outgoing(player);
}

void update_furnace(struct world* world, struct tile_entity* te) {
	struct slot* si = getSlot(NULL, te->data.furnace.inv, 0);
	struct slot* fu = getSlot(NULL, te->data.furnace.inv, 1);
	struct slot* aso = getSlot(NULL, te->data.furnace.inv, 2);
	struct slot* so = getSmeltingOutput(si);
	int16_t st = getSmeltingFuelBurnTime(fu);
	int burning = 0;
	if (so != NULL && ((itemsStackable(so, aso) && (aso->itemCount + so->itemCount) <= maxStackSize(so)) || aso == NULL) && (te->data.furnace.burnTime > 0 || st > 0)) {
		burning = 1;
		if (!te->tick) {
			te->tick = &tetick_furnace;
			enableTileEntityTickable(world, te);
		}
		printf("bt = %i\n", te->data.furnace.burnTime);
		if (te->data.furnace.burnTime <= 0 && st > 0 && fu != NULL) {
			te->data.furnace.burnTime += st;
			if (--fu->itemCount == 0) fu = NULL;
			setSlot(NULL, te->data.furnace.inv, 1, fu, 1, 1);
			te->data.furnace.lastBurnMax = st;
			BEGIN_BROADCAST(te->data.furnace.inv->players)
			struct packet* pkt = xmalloc(sizeof(struct packet));
			pkt->id = PKT_PLAY_CLIENT_WINDOWPROPERTY;
			pkt->data.play_client.windowproperty.window_id = te->data.furnace.inv->windowID;
			pkt->data.play_client.windowproperty.property = 1;
			pkt->data.play_client.windowproperty.value = te->data.furnace.lastBurnMax;
			add_queue(bc_player->outgoingPacket, pkt);
			flush_outgoing (bc_player);
			END_BROADCAST
		}
		if (te->data.furnace.cookTime <= 0) {
			printf("start cookin\n");
			te->data.furnace.cookTime++;
		} else if (te->data.furnace.cookTime < 200) {
			printf("cookin %i/%i\n", te->data.furnace.cookTime, 200);
			te->data.furnace.cookTime++;
		} else if (te->data.furnace.cookTime == 200) {
			te->data.furnace.cookTime = 0;
			printf("donecookin\n");
			if (aso == NULL) setSlot(NULL, te->data.furnace.inv, 2, so, 1, 1);
			else {
				aso->itemCount++;
				setSlot(NULL, te->data.furnace.inv, 2, aso, 1, 1);
			}
			if (--si->itemCount == 0) si = NULL;
			setSlot(NULL, te->data.furnace.inv, 0, si, 1, 1);
			te->data.furnace.burnTime++; // freebie for accounting
		}
	} else te->data.furnace.cookTime = 0;
	if (te->data.furnace.burnTime > 0) {
		te->data.furnace.burnTime--;
	} else {
		if (te->tick) {
			BEGIN_BROADCAST(te->data.furnace.inv->players)
			struct packet* pkt = xmalloc(sizeof(struct packet));
			pkt->id = PKT_PLAY_CLIENT_WINDOWPROPERTY;
			pkt->data.play_client.windowproperty.window_id = te->data.furnace.inv->windowID;
			pkt->data.play_client.windowproperty.property = 0;
			pkt->data.play_client.windowproperty.value = 0;
			add_queue(bc_player->outgoingPacket, pkt);
			flush_outgoing (bc_player);
			pkt = xmalloc(sizeof(struct packet));
			pkt->id = PKT_PLAY_CLIENT_WINDOWPROPERTY;
			pkt->data.play_client.windowproperty.window_id = te->data.furnace.inv->windowID;
			pkt->data.play_client.windowproperty.property = 2;
			pkt->data.play_client.windowproperty.value = 0;
			add_queue(bc_player->outgoingPacket, pkt);
			flush_outgoing(bc_player);
			END_BROADCAST disableTileEntityTickable(world, te);
			te->tick = NULL;
		}
		te->data.furnace.cookTime = 0;
	}
	if (burning && tick_counter % 5 == 0) {
		BEGIN_BROADCAST(te->data.furnace.inv->players)
		struct packet* pkt = xmalloc(sizeof(struct packet));
		pkt->id = PKT_PLAY_CLIENT_WINDOWPROPERTY;
		pkt->data.play_client.windowproperty.window_id = te->data.furnace.inv->windowID;
		pkt->data.play_client.windowproperty.property = 0;
		pkt->data.play_client.windowproperty.value = te->data.furnace.burnTime;
		add_queue(bc_player->outgoingPacket, pkt);
		flush_outgoing (bc_player);
		pkt = xmalloc(sizeof(struct packet));
		pkt->id = PKT_PLAY_CLIENT_WINDOWPROPERTY;
		pkt->data.play_client.windowproperty.window_id = te->data.furnace.inv->windowID;
		pkt->data.play_client.windowproperty.property = 2;
		pkt->data.play_client.windowproperty.value = te->data.furnace.cookTime;
		add_queue(bc_player->outgoingPacket, pkt);
		flush_outgoing(bc_player);
		END_BROADCAST
	}
}

struct block_info* getBlockInfo(block b) {
	if (block_infos[b].material > 0) return &block_infos[b];
	return &block_infos[(b >> 4) << 4];
}

// index = item ID
const char* nameToIDMap[] = { "minecraft:air", "minecraft:stone", "minecraft:grass", "minecraft:dirt", "minecraft:cobblestone", "minecraft:planks", "minecraft:sapling", "minecraft:bedrock", "", "", "", "", "minecraft:sand", "minecraft:gravel", "minecraft:gold_ore", "minecraft:iron_ore", "minecraft:coal_ore", "minecraft:log", "minecraft:leaves", "minecraft:sponge", "minecraft:glass", "minecraft:lapis_ore", "minecraft:lapis_block", "minecraft:dispenser", "minecraft:sandstone", "minecraft:noteblock", "", "minecraft:golden_rail", "minecraft:detector_rail", "minecraft:sticky_piston", "minecraft:web", "minecraft:tallgrass", "minecraft:deadbush", "minecraft:piston", "", "minecraft:wool", "", "minecraft:yellow_flower", "minecraft:red_flower", "minecraft:brown_mushroom", "minecraft:red_mushroom", "minecraft:gold_block", "minecraft:iron_block", "", "minecraft:stone_slab", "minecraft:brick_block", "minecraft:tnt", "minecraft:bookshelf", "minecraft:mossy_cobblestone", "minecraft:obsidian",
		"minecraft:torch", "", "minecraft:mob_spawner", "minecraft:oak_stairs", "minecraft:chest", "", "minecraft:diamond_ore", "minecraft:diamond_block", "minecraft:crafting_table", "", "minecraft:farmland", "minecraft:furnace", "", "", "", "minecraft:ladder", "minecraft:rail", "minecraft:stone_stairs", "", "minecraft:lever", "minecraft:stone_pressure_plate", "", "minecraft:wooden_pressure_plate", "minecraft:redstone_ore", "", "", "minecraft:redstone_torch", "minecraft:stone_button", "minecraft:snow_layer", "minecraft:ice", "minecraft:snow", "minecraft:cactus", "minecraft:clay", "", "minecraft:jukebox", "minecraft:fence", "minecraft:pumpkin", "minecraft:netherrack", "minecraft:soul_sand", "minecraft:glowstone", "", "minecraft:lit_pumpkin", "", "", "", "minecraft:stained_glass", "minecraft:trapdoor", "minecraft:monster_egg", "minecraft:stonebrick", "minecraft:brown_mushroom_block", "minecraft:red_mushroom_block", "minecraft:iron_bars", "minecraft:glass_pane", "minecraft:melon_block",
		"", "", "minecraft:vine", "minecraft:fence_gate", "minecraft:brick_stairs", "minecraft:stone_brick_stairs", "minecraft:mycelium", "minecraft:waterlily", "minecraft:nether_brick", "minecraft:nether_brick_fence", "minecraft:nether_brick_stairs", "", "minecraft:enchanting_table", "", "", "", "minecraft:end_portal_frame", "minecraft:end_stone", "minecraft:dragon_egg", "minecraft:redstone_lamp", "", "", "minecraft:wooden_slab", "", "minecraft:sandstone_stairs", "minecraft:emerald_ore", "minecraft:ender_chest", "minecraft:tripwire_hook", "", "minecraft:emerald_block", "minecraft:spruce_stairs", "minecraft:birch_stairs", "minecraft:jungle_stairs", "minecraft:command_block", "minecraft:beacon", "minecraft:cobblestone_wall", "", "", "", "minecraft:wooden_button", "", "minecraft:anvil", "minecraft:trapped_chest", "minecraft:light_weighted_pressure_plate", "minecraft:heavy_weighted_pressure_plate", "", "", "minecraft:daylight_detector", "minecraft:redstone_block", "minecraft:quartz_ore",
		"minecraft:hopper", "minecraft:quartz_block", "minecraft:quartz_stairs", "minecraft:activator_rail", "minecraft:dropper", "minecraft:stained_hardened_clay", "minecraft:stained_glass_pane", "minecraft:leaves2", "minecraft:log2", "minecraft:acacia_stairs", "minecraft:dark_oak_stairs", "minecraft:slime", "minecraft:barrier", "minecraft:iron_trapdoor", "minecraft:prismarine", "minecraft:sea_lantern", "minecraft:hay_block", "minecraft:carpet", "minecraft:hardened_clay", "minecraft:coal_block", "minecraft:packed_ice", "minecraft:double_plant", "", "", "", "minecraft:red_sandstone", "minecraft:red_sandstone_stairs", "", "minecraft:stone_slab2", "minecraft:spruce_fence_gate", "minecraft:birch_fence_gate", "minecraft:jungle_fence_gate", "minecraft:dark_oak_fence_gate", "minecraft:acacia_fence_gate", "minecraft:spruce_fence", "minecraft:birch_fence", "minecraft:jungle_fence", "minecraft:dark_oak_fence", "minecraft:acacia_fence", "", "", "", "", "", "minecraft:end_rod",
		"minecraft:chorus_plant", "minecraft:chorus_flower", "minecraft:purpur_block", "minecraft:purpur_pillar", "minecraft:purpur_stairs", "", "minecraft:purpur_slab", "minecraft:end_bricks", "", "minecraft:grass_path", "", "minecraft:repeating_command_block", "minecraft:chain_command_block", "", "minecraft:magma", "minecraft:nether_wart_block", "minecraft:red_nether_brick", "minecraft:bone_block", "minecraft:structure_void", "minecraft:observer", "minecraft:white_shulker_box", "minecraft:orange_shulker_box", "minecraft:magenta_shulker_box", "minecraft:light_blue_shulker_box", "minecraft:yellow_shulker_box", "minecraft:lime_shulker_box", "minecraft:pink_shulker_box", "minecraft:gray_shulker_box", "minecraft:silver_shulker_box", "minecraft:cyan_shulker_box", "minecraft:purple_shulker_box", "minecraft:blue_shulker_box", "minecraft:brown_shulker_box", "minecraft:green_shulker_box", "minecraft:red_shulker_box", "minecraft:black_shulker_box", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "minecraft:structure_block", "minecraft:iron_shovel", "minecraft:iron_pickaxe", "minecraft:iron_axe", "minecraft:flint_and_steel", "minecraft:apple", "minecraft:bow", "minecraft:arrow", "minecraft:coal", "minecraft:diamond", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:iron_sword", "minecraft:wooden_sword", "minecraft:wooden_shovel", "minecraft:wooden_pickaxe", "minecraft:wooden_axe", "minecraft:stone_sword", "minecraft:stone_shovel", "minecraft:stone_pickaxe", "minecraft:stone_axe", "minecraft:diamond_sword", "minecraft:diamond_shovel", "minecraft:diamond_pickaxe", "minecraft:diamond_axe", "minecraft:stick", "minecraft:bowl", "minecraft:mushroom_stew", "minecraft:golden_sword", "minecraft:golden_shovel", "minecraft:golden_pickaxe", "minecraft:golden_axe", "minecraft:string", "minecraft:feather", "minecraft:gunpowder", "minecraft:wooden_hoe", "minecraft:stone_hoe", "minecraft:iron_hoe", "minecraft:diamond_hoe",
		"minecraft:golden_hoe", "minecraft:wheat_seeds", "minecraft:wheat", "minecraft:bread", "minecraft:leather_helmet", "minecraft:leather_chestplate", "minecraft:leather_leggings", "minecraft:leather_boots", "minecraft:chainmail_helmet", "minecraft:chainmail_chestplate", "minecraft:chainmail_leggings", "minecraft:chainmail_boots", "minecraft:iron_helmet", "minecraft:iron_chestplate", "minecraft:iron_leggings", "minecraft:iron_boots", "minecraft:diamond_helmet", "minecraft:diamond_chestplate", "minecraft:diamond_leggings", "minecraft:diamond_boots", "minecraft:golden_helmet", "minecraft:golden_chestplate", "minecraft:golden_leggings", "minecraft:golden_boots", "minecraft:flint", "minecraft:porkchop", "minecraft:cooked_porkchop", "minecraft:painting", "minecraft:golden_apple", "minecraft:sign", "minecraft:wooden_door", "minecraft:bucket", "minecraft:water_bucket", "minecraft:lava_bucket", "minecraft:minecart", "minecraft:saddle", "minecraft:iron_door", "minecraft:redstone",
		"minecraft:snowball", "minecraft:boat", "minecraft:leather", "minecraft:milk_bucket", "minecraft:brick", "minecraft:clay_ball", "minecraft:reeds", "minecraft:paper", "minecraft:book", "minecraft:slime_ball", "minecraft:chest_minecart", "minecraft:furnace_minecart", "minecraft:egg", "minecraft:compass", "minecraft:fishing_rod", "minecraft:clock", "minecraft:glowstone_dust", "minecraft:fish", "minecraft:cooked_fish", "minecraft:dye", "minecraft:bone", "minecraft:sugar", "minecraft:cake", "minecraft:bed", "minecraft:repeater", "minecraft:cookie", "minecraft:filled_map", "minecraft:shears", "minecraft:melon", "minecraft:pumpkin_seeds", "minecraft:melon_seeds", "minecraft:beef", "minecraft:cooked_beef", "minecraft:chicken", "minecraft:cooked_chicken", "minecraft:rotten_flesh", "minecraft:ender_pearl", "minecraft:blaze_rod", "minecraft:ghast_tear", "minecraft:gold_nugget", "minecraft:nether_wart", "minecraft:potion", "minecraft:glass_bottle", "minecraft:spider_eye",
		"minecraft:fermented_spider_eye", "minecraft:blaze_powder", "minecraft:magma_cream", "minecraft:brewing_stand", "minecraft:cauldron", "minecraft:ender_eye", "minecraft:speckled_melon", "minecraft:spawn_egg", "minecraft:experience_bottle", "minecraft:fire_charge", "minecraft:writable_book", "minecraft:written_book", "minecraft:emerald", "minecraft:item_frame", "minecraft:flower_pot", "minecraft:carrot", "minecraft:potato", "minecraft:baked_potato", "minecraft:poisonous_potato", "minecraft:map", "minecraft:golden_carrot", "minecraft:skull", "minecraft:carrot_on_a_stick", "minecraft:nether_star", "minecraft:pumpkin_pie", "minecraft:fireworks", "minecraft:firework_charge", "minecraft:enchanted_book", "minecraft:comparator", "minecraft:netherbrick", "minecraft:quartz", "minecraft:tnt_minecart", "minecraft:hopper_minecart", "minecraft:prismarine_shard", "minecraft:prismarine_crystals", "minecraft:rabbit", "minecraft:cooked_rabbit", "minecraft:rabbit_stew", "minecraft:rabbit_foot",
		"minecraft:rabbit_hide", "minecraft:armor_stand", "minecraft:iron_horse_armor", "minecraft:golden_horse_armor", "minecraft:diamond_horse_armor", "minecraft:lead", "minecraft:name_tag", "minecraft:command_block_minecart", "minecraft:mutton", "minecraft:cooked_mutton", "", "minecraft:end_crystal", "minecraft:spruce_door", "minecraft:birch_door", "minecraft:jungle_door", "minecraft:acacia_door", "minecraft:dark_oak_door", "minecraft:chorus_fruit", "minecraft:chorus_fruit_popped", "minecraft:beetroot", "minecraft:beetroot_seeds", "minecraft:beetroot_soup", "minecraft:dragon_breath", "minecraft:splash_potion", "minecraft:spectral_arrow", "minecraft:tipped_arrow", "minecraft:lingering_potion", "minecraft:shield", "minecraft:elytra", "minecraft:spruce_boat", "minecraft:birch_boat", "minecraft:jungle_boat", "minecraft:acacia_boat", "minecraft:dark_oak_boat", "minecraft:totem", "minecraft:shulker_shell", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
		"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "minecraft:record_13", "minecraft:record_cat", "minecraft:record_blocks", "minecraft:record_chirp", "minecraft:record_far", "minecraft:record_mall", "minecraft:record_mellohi", "minecraft:record_stal", "minecraft:record_strad", "minecraft:record_ward", "minecraft:record_11", "minecraft:record_wait" };

int16_t getItemFromName(const char* name) {
	for (size_t i = 0; i < (sizeof(nameToIDMap) / sizeof(char*)); i++) {
		if (streq_nocase(nameToIDMap[i], name)) return i;
	}
	return -1;
}

void init_blocks() {
	block_materials[MAT_AIR].flammable = 0;
	block_materials[MAT_AIR].replacable = 1;
	block_materials[MAT_AIR].requiresnotool = 1;
	block_materials[MAT_AIR].mobility = 0;
	block_materials[MAT_AIR].adventure_exempt = 0;
	block_materials[MAT_AIR].liquid = 0;
	block_materials[MAT_AIR].solid = 0;
	block_materials[MAT_AIR].blocksLight = 0;
	block_materials[MAT_AIR].blocksMovement = 0;
	block_materials[MAT_GRASS].flammable = 0;
	block_materials[MAT_GRASS].replacable = 0;
	block_materials[MAT_GRASS].requiresnotool = 1;
	block_materials[MAT_GRASS].mobility = 0;
	block_materials[MAT_GRASS].adventure_exempt = 0;
	block_materials[MAT_GRASS].liquid = 0;
	block_materials[MAT_GRASS].solid = 1;
	block_materials[MAT_GRASS].blocksLight = 1;
	block_materials[MAT_GRASS].blocksMovement = 1;
	block_materials[MAT_GROUND].flammable = 0;
	block_materials[MAT_GROUND].replacable = 0;
	block_materials[MAT_GROUND].requiresnotool = 1;
	block_materials[MAT_GROUND].mobility = 0;
	block_materials[MAT_GROUND].adventure_exempt = 0;
	block_materials[MAT_GROUND].liquid = 0;
	block_materials[MAT_GROUND].solid = 1;
	block_materials[MAT_GROUND].blocksLight = 1;
	block_materials[MAT_GROUND].blocksMovement = 1;
	block_materials[MAT_WOOD].flammable = 1;
	block_materials[MAT_WOOD].replacable = 0;
	block_materials[MAT_WOOD].requiresnotool = 1;
	block_materials[MAT_WOOD].mobility = 0;
	block_materials[MAT_WOOD].adventure_exempt = 0;
	block_materials[MAT_WOOD].liquid = 0;
	block_materials[MAT_WOOD].solid = 1;
	block_materials[MAT_WOOD].blocksLight = 1;
	block_materials[MAT_WOOD].blocksMovement = 1;
	block_materials[MAT_ROCK].flammable = 0;
	block_materials[MAT_ROCK].replacable = 0;
	block_materials[MAT_ROCK].requiresnotool = 0;
	block_materials[MAT_ROCK].mobility = 0;
	block_materials[MAT_ROCK].adventure_exempt = 0;
	block_materials[MAT_ROCK].liquid = 0;
	block_materials[MAT_ROCK].solid = 1;
	block_materials[MAT_ROCK].blocksLight = 1;
	block_materials[MAT_ROCK].blocksMovement = 1;
	block_materials[MAT_IRON].flammable = 0;
	block_materials[MAT_IRON].replacable = 0;
	block_materials[MAT_IRON].requiresnotool = 0;
	block_materials[MAT_IRON].mobility = 0;
	block_materials[MAT_IRON].adventure_exempt = 0;
	block_materials[MAT_IRON].liquid = 0;
	block_materials[MAT_IRON].solid = 1;
	block_materials[MAT_IRON].blocksLight = 1;
	block_materials[MAT_IRON].blocksMovement = 1;
	block_materials[MAT_ANVIL].flammable = 0;
	block_materials[MAT_ANVIL].replacable = 0;
	block_materials[MAT_ANVIL].requiresnotool = 0;
	block_materials[MAT_ANVIL].mobility = 2;
	block_materials[MAT_ANVIL].adventure_exempt = 0;
	block_materials[MAT_ANVIL].liquid = 0;
	block_materials[MAT_ANVIL].solid = 1;
	block_materials[MAT_ANVIL].blocksLight = 1;
	block_materials[MAT_ANVIL].blocksMovement = 1;
	block_materials[MAT_WATER].flammable = 0;
	block_materials[MAT_WATER].replacable = 1;
	block_materials[MAT_WATER].requiresnotool = 1;
	block_materials[MAT_WATER].mobility = 1;
	block_materials[MAT_WATER].adventure_exempt = 0;
	block_materials[MAT_WATER].liquid = 1;
	block_materials[MAT_WATER].solid = 0;
	block_materials[MAT_WATER].blocksLight = 1;
	block_materials[MAT_WATER].blocksMovement = 0;
	block_materials[MAT_LAVA].flammable = 0;
	block_materials[MAT_LAVA].replacable = 1;
	block_materials[MAT_LAVA].requiresnotool = 1;
	block_materials[MAT_LAVA].mobility = 1;
	block_materials[MAT_LAVA].adventure_exempt = 0;
	block_materials[MAT_LAVA].liquid = 1;
	block_materials[MAT_LAVA].solid = 0;
	block_materials[MAT_LAVA].blocksLight = 1;
	block_materials[MAT_LAVA].blocksMovement = 0;
	block_materials[MAT_LEAVES].flammable = 1;
	block_materials[MAT_LEAVES].replacable = 0;
	block_materials[MAT_LEAVES].requiresnotool = 1;
	block_materials[MAT_LEAVES].mobility = 1;
	block_materials[MAT_LEAVES].adventure_exempt = 0;
	block_materials[MAT_LEAVES].liquid = 0;
	block_materials[MAT_LEAVES].solid = 1;
	block_materials[MAT_LEAVES].blocksLight = 1;
	block_materials[MAT_LEAVES].blocksMovement = 1;
	block_materials[MAT_PLANTS].flammable = 0;
	block_materials[MAT_PLANTS].replacable = 0;
	block_materials[MAT_PLANTS].requiresnotool = 1;
	block_materials[MAT_PLANTS].mobility = 1;
	block_materials[MAT_PLANTS].adventure_exempt = 1;
	block_materials[MAT_PLANTS].liquid = 0;
	block_materials[MAT_PLANTS].solid = 0;
	block_materials[MAT_PLANTS].blocksLight = 0;
	block_materials[MAT_PLANTS].blocksMovement = 0;
	block_materials[MAT_VINE].flammable = 1;
	block_materials[MAT_VINE].replacable = 1;
	block_materials[MAT_VINE].requiresnotool = 1;
	block_materials[MAT_VINE].mobility = 1;
	block_materials[MAT_VINE].adventure_exempt = 1;
	block_materials[MAT_VINE].liquid = 0;
	block_materials[MAT_VINE].solid = 0;
	block_materials[MAT_VINE].blocksLight = 0;
	block_materials[MAT_VINE].blocksMovement = 0;
	block_materials[MAT_SPONGE].flammable = 0;
	block_materials[MAT_SPONGE].replacable = 0;
	block_materials[MAT_SPONGE].requiresnotool = 1;
	block_materials[MAT_SPONGE].mobility = 0;
	block_materials[MAT_SPONGE].adventure_exempt = 0;
	block_materials[MAT_SPONGE].liquid = 0;
	block_materials[MAT_SPONGE].solid = 1;
	block_materials[MAT_SPONGE].blocksLight = 1;
	block_materials[MAT_SPONGE].blocksMovement = 1;
	block_materials[MAT_CLOTH].flammable = 1;
	block_materials[MAT_CLOTH].replacable = 0;
	block_materials[MAT_CLOTH].requiresnotool = 1;
	block_materials[MAT_CLOTH].mobility = 0;
	block_materials[MAT_CLOTH].adventure_exempt = 0;
	block_materials[MAT_CLOTH].liquid = 0;
	block_materials[MAT_CLOTH].solid = 1;
	block_materials[MAT_CLOTH].blocksLight = 1;
	block_materials[MAT_CLOTH].blocksMovement = 1;
	block_materials[MAT_FIRE].flammable = 0;
	block_materials[MAT_FIRE].replacable = 1;
	block_materials[MAT_FIRE].requiresnotool = 1;
	block_materials[MAT_FIRE].mobility = 1;
	block_materials[MAT_FIRE].adventure_exempt = 0;
	block_materials[MAT_FIRE].liquid = 0;
	block_materials[MAT_FIRE].solid = 0;
	block_materials[MAT_FIRE].blocksLight = 0;
	block_materials[MAT_FIRE].blocksMovement = 0;
	block_materials[MAT_SAND].flammable = 0;
	block_materials[MAT_SAND].replacable = 0;
	block_materials[MAT_SAND].requiresnotool = 1;
	block_materials[MAT_SAND].mobility = 0;
	block_materials[MAT_SAND].adventure_exempt = 0;
	block_materials[MAT_SAND].liquid = 0;
	block_materials[MAT_SAND].solid = 1;
	block_materials[MAT_SAND].blocksLight = 1;
	block_materials[MAT_SAND].blocksMovement = 1;
	block_materials[MAT_CIRCUITS].flammable = 0;
	block_materials[MAT_CIRCUITS].replacable = 0;
	block_materials[MAT_CIRCUITS].requiresnotool = 1;
	block_materials[MAT_CIRCUITS].mobility = 1;
	block_materials[MAT_CIRCUITS].adventure_exempt = 1;
	block_materials[MAT_CIRCUITS].liquid = 0;
	block_materials[MAT_CIRCUITS].solid = 0;
	block_materials[MAT_CIRCUITS].blocksLight = 0;
	block_materials[MAT_CIRCUITS].blocksMovement = 0;
	block_materials[MAT_CARPET].flammable = 1;
	block_materials[MAT_CARPET].replacable = 0;
	block_materials[MAT_CARPET].requiresnotool = 1;
	block_materials[MAT_CARPET].mobility = 0;
	block_materials[MAT_CARPET].adventure_exempt = 1;
	block_materials[MAT_CARPET].liquid = 0;
	block_materials[MAT_CARPET].solid = 0;
	block_materials[MAT_CARPET].blocksLight = 0;
	block_materials[MAT_CARPET].blocksMovement = 0;
	block_materials[MAT_GLASS].flammable = 0;
	block_materials[MAT_GLASS].replacable = 0;
	block_materials[MAT_GLASS].requiresnotool = 1;
	block_materials[MAT_GLASS].mobility = 0;
	block_materials[MAT_GLASS].adventure_exempt = 1;
	block_materials[MAT_GLASS].liquid = 0;
	block_materials[MAT_GLASS].solid = 1;
	block_materials[MAT_GLASS].blocksLight = 1;
	block_materials[MAT_GLASS].blocksMovement = 1;
	block_materials[MAT_REDSTONE_LIGHT].flammable = 0;
	block_materials[MAT_REDSTONE_LIGHT].replacable = 0;
	block_materials[MAT_REDSTONE_LIGHT].requiresnotool = 1;
	block_materials[MAT_REDSTONE_LIGHT].mobility = 0;
	block_materials[MAT_REDSTONE_LIGHT].adventure_exempt = 1;
	block_materials[MAT_REDSTONE_LIGHT].liquid = 0;
	block_materials[MAT_REDSTONE_LIGHT].solid = 1;
	block_materials[MAT_REDSTONE_LIGHT].blocksLight = 1;
	block_materials[MAT_REDSTONE_LIGHT].blocksMovement = 1;
	block_materials[MAT_TNT].flammable = 1;
	block_materials[MAT_TNT].replacable = 0;
	block_materials[MAT_TNT].requiresnotool = 1;
	block_materials[MAT_TNT].mobility = 0;
	block_materials[MAT_TNT].adventure_exempt = 0;
	block_materials[MAT_TNT].liquid = 0;
	block_materials[MAT_TNT].solid = 1;
	block_materials[MAT_TNT].blocksLight = 1;
	block_materials[MAT_TNT].blocksMovement = 1;
	block_materials[MAT_CORAL].flammable = 0;
	block_materials[MAT_CORAL].replacable = 0;
	block_materials[MAT_CORAL].requiresnotool = 1;
	block_materials[MAT_CORAL].mobility = 1;
	block_materials[MAT_CORAL].adventure_exempt = 0;
	block_materials[MAT_CORAL].liquid = 0;
	block_materials[MAT_CORAL].solid = 1;
	block_materials[MAT_CORAL].blocksLight = 1;
	block_materials[MAT_CORAL].blocksMovement = 1;
	block_materials[MAT_ICE].flammable = 0;
	block_materials[MAT_ICE].replacable = 0;
	block_materials[MAT_ICE].requiresnotool = 1;
	block_materials[MAT_ICE].mobility = 0;
	block_materials[MAT_ICE].adventure_exempt = 1;
	block_materials[MAT_ICE].liquid = 0;
	block_materials[MAT_ICE].solid = 1;
	block_materials[MAT_ICE].blocksLight = 1;
	block_materials[MAT_ICE].blocksMovement = 1;
	block_materials[MAT_PACKED_ICE].flammable = 0;
	block_materials[MAT_PACKED_ICE].replacable = 0;
	block_materials[MAT_PACKED_ICE].requiresnotool = 1;
	block_materials[MAT_PACKED_ICE].mobility = 0;
	block_materials[MAT_PACKED_ICE].adventure_exempt = 1;
	block_materials[MAT_PACKED_ICE].liquid = 0;
	block_materials[MAT_PACKED_ICE].solid = 1;
	block_materials[MAT_PACKED_ICE].blocksLight = 1;
	block_materials[MAT_PACKED_ICE].blocksMovement = 1;
	block_materials[MAT_SNOW].flammable = 0;
	block_materials[MAT_SNOW].replacable = 1;
	block_materials[MAT_SNOW].requiresnotool = 0;
	block_materials[MAT_SNOW].mobility = 1;
	block_materials[MAT_SNOW].adventure_exempt = 1;
	block_materials[MAT_SNOW].liquid = 0;
	block_materials[MAT_SNOW].solid = 0;
	block_materials[MAT_SNOW].blocksLight = 0;
	block_materials[MAT_SNOW].blocksMovement = 0;
	block_materials[MAT_CRAFTED_SNOW].flammable = 0;
	block_materials[MAT_CRAFTED_SNOW].replacable = 0;
	block_materials[MAT_CRAFTED_SNOW].requiresnotool = 0;
	block_materials[MAT_CRAFTED_SNOW].mobility = 0;
	block_materials[MAT_CRAFTED_SNOW].adventure_exempt = 0;
	block_materials[MAT_CRAFTED_SNOW].liquid = 0;
	block_materials[MAT_CRAFTED_SNOW].solid = 1;
	block_materials[MAT_CRAFTED_SNOW].blocksLight = 1;
	block_materials[MAT_CRAFTED_SNOW].blocksMovement = 1;
	block_materials[MAT_CACTUS].flammable = 0;
	block_materials[MAT_CACTUS].replacable = 0;
	block_materials[MAT_CACTUS].requiresnotool = 1;
	block_materials[MAT_CACTUS].mobility = 1;
	block_materials[MAT_CACTUS].adventure_exempt = 0;
	block_materials[MAT_CACTUS].liquid = 0;
	block_materials[MAT_CACTUS].solid = 1;
	block_materials[MAT_CACTUS].blocksLight = 1;
	block_materials[MAT_CACTUS].blocksMovement = 1;
	block_materials[MAT_CLAY].flammable = 0;
	block_materials[MAT_CLAY].replacable = 0;
	block_materials[MAT_CLAY].requiresnotool = 1;
	block_materials[MAT_CLAY].mobility = 0;
	block_materials[MAT_CLAY].adventure_exempt = 0;
	block_materials[MAT_CLAY].liquid = 0;
	block_materials[MAT_CLAY].solid = 1;
	block_materials[MAT_CLAY].blocksLight = 1;
	block_materials[MAT_CLAY].blocksMovement = 1;
	block_materials[MAT_GOURD].flammable = 0;
	block_materials[MAT_GOURD].replacable = 0;
	block_materials[MAT_GOURD].requiresnotool = 1;
	block_materials[MAT_GOURD].mobility = 1;
	block_materials[MAT_GOURD].adventure_exempt = 0;
	block_materials[MAT_GOURD].liquid = 0;
	block_materials[MAT_GOURD].solid = 1;
	block_materials[MAT_GOURD].blocksLight = 1;
	block_materials[MAT_GOURD].blocksMovement = 1;
	block_materials[MAT_DRAGON_EGG].flammable = 0;
	block_materials[MAT_DRAGON_EGG].replacable = 0;
	block_materials[MAT_DRAGON_EGG].requiresnotool = 1;
	block_materials[MAT_DRAGON_EGG].mobility = 1;
	block_materials[MAT_DRAGON_EGG].adventure_exempt = 0;
	block_materials[MAT_DRAGON_EGG].liquid = 0;
	block_materials[MAT_DRAGON_EGG].solid = 1;
	block_materials[MAT_DRAGON_EGG].blocksLight = 1;
	block_materials[MAT_DRAGON_EGG].blocksMovement = 1;
	block_materials[MAT_PORTAL].flammable = 0;
	block_materials[MAT_PORTAL].replacable = 0;
	block_materials[MAT_PORTAL].requiresnotool = 1;
	block_materials[MAT_PORTAL].mobility = 2;
	block_materials[MAT_PORTAL].adventure_exempt = 0;
	block_materials[MAT_PORTAL].liquid = 0;
	block_materials[MAT_PORTAL].solid = 0;
	block_materials[MAT_PORTAL].blocksLight = 0;
	block_materials[MAT_PORTAL].blocksMovement = 0;
	block_materials[MAT_CAKE].flammable = 0;
	block_materials[MAT_CAKE].replacable = 0;
	block_materials[MAT_CAKE].requiresnotool = 1;
	block_materials[MAT_CAKE].mobility = 1;
	block_materials[MAT_CAKE].adventure_exempt = 0;
	block_materials[MAT_CAKE].liquid = 0;
	block_materials[MAT_CAKE].solid = 1;
	block_materials[MAT_CAKE].blocksLight = 1;
	block_materials[MAT_CAKE].blocksMovement = 1;
	block_materials[MAT_WEB].flammable = 0;
	block_materials[MAT_WEB].replacable = 0;
	block_materials[MAT_WEB].requiresnotool = 0;
	block_materials[MAT_WEB].mobility = 1;
	block_materials[MAT_WEB].adventure_exempt = 0;
	block_materials[MAT_WEB].liquid = 0;
	block_materials[MAT_WEB].solid = 1;
	block_materials[MAT_WEB].blocksLight = 1;
	block_materials[MAT_WEB].blocksMovement = 0;
	block_materials[MAT_PISTON].flammable = 0;
	block_materials[MAT_PISTON].replacable = 0;
	block_materials[MAT_PISTON].requiresnotool = 1;
	block_materials[MAT_PISTON].mobility = 2;
	block_materials[MAT_PISTON].adventure_exempt = 0;
	block_materials[MAT_PISTON].liquid = 0;
	block_materials[MAT_PISTON].solid = 1;
	block_materials[MAT_PISTON].blocksLight = 1;
	block_materials[MAT_PISTON].blocksMovement = 1;
	block_materials[MAT_BARRIER].flammable = 0;
	block_materials[MAT_BARRIER].replacable = 0;
	block_materials[MAT_BARRIER].requiresnotool = 0;
	block_materials[MAT_BARRIER].mobility = 2;
	block_materials[MAT_BARRIER].adventure_exempt = 0;
	block_materials[MAT_BARRIER].liquid = 0;
	block_materials[MAT_BARRIER].solid = 1;
	block_materials[MAT_BARRIER].blocksLight = 1;
	block_materials[MAT_BARRIER].blocksMovement = 1;
	block_materials[MAT_STRUCTURE_VOID].flammable = 0;
	block_materials[MAT_STRUCTURE_VOID].replacable = 1;
	block_materials[MAT_STRUCTURE_VOID].requiresnotool = 1;
	block_materials[MAT_STRUCTURE_VOID].mobility = 0;
	block_materials[MAT_STRUCTURE_VOID].adventure_exempt = 0;
	block_materials[MAT_STRUCTURE_VOID].liquid = 0;
	block_materials[MAT_STRUCTURE_VOID].solid = 0;
	block_materials[MAT_STRUCTURE_VOID].blocksLight = 0;
	block_materials[MAT_STRUCTURE_VOID].blocksMovement = 0;
//
	block_infos[BLK_AIR].hardness = 0.0;
	block_infos[BLK_AIR].material = MAT_AIR;
	block_infos[BLK_AIR].slipperiness = 0.6;
	block_infos[BLK_STONE].hardness = 1.5;
	block_infos[BLK_STONE].material = MAT_ROCK;
	block_infos[BLK_STONE].slipperiness = 0.6;
	block_infos[BLK_GRASS].hardness = 0.6;
	block_infos[BLK_GRASS].material = MAT_GRASS;
	block_infos[BLK_GRASS].slipperiness = 0.6;
	block_infos[BLK_DIRT].hardness = 0.5;
	block_infos[BLK_DIRT].material = MAT_GROUND;
	block_infos[BLK_DIRT].slipperiness = 0.6;
	block_infos[BLK_STONEBRICK].hardness = 2.0;
	block_infos[BLK_STONEBRICK].material = MAT_ROCK;
	block_infos[BLK_STONEBRICK].slipperiness = 0.6;
	block_infos[BLK_WOOD_OAK].hardness = 2.0;
	block_infos[BLK_WOOD_OAK].material = MAT_WOOD;
	block_infos[BLK_WOOD_OAK].slipperiness = 0.6;
	block_infos[BLK_SAPLING_OAK].hardness = 0.0;
	block_infos[BLK_SAPLING_OAK].material = MAT_PLANTS;
	block_infos[BLK_SAPLING_OAK].slipperiness = 0.6;
	block_infos[BLK_BEDROCK].hardness = -1.0;
	block_infos[BLK_BEDROCK].material = MAT_ROCK;
	block_infos[BLK_BEDROCK].slipperiness = 0.6;
	block_infos[BLK_SAND].hardness = 0.5;
	block_infos[BLK_SAND].material = MAT_SAND;
	block_infos[BLK_SAND].slipperiness = 0.6;
	block_infos[BLK_GRAVEL].hardness = 0.6;
	block_infos[BLK_GRAVEL].material = MAT_SAND;
	block_infos[BLK_GRAVEL].slipperiness = 0.6;
	block_infos[BLK_OREGOLD].hardness = 3.0;
	block_infos[BLK_OREGOLD].material = MAT_ROCK;
	block_infos[BLK_OREGOLD].slipperiness = 0.6;
	block_infos[BLK_OREIRON].hardness = 3.0;
	block_infos[BLK_OREIRON].material = MAT_ROCK;
	block_infos[BLK_OREIRON].slipperiness = 0.6;
	block_infos[BLK_ORECOAL].hardness = 3.0;
	block_infos[BLK_ORECOAL].material = MAT_ROCK;
	block_infos[BLK_ORECOAL].slipperiness = 0.6;
	block_infos[BLK_LOG_OAK].hardness = 2.0;
	block_infos[BLK_LOG_OAK].material = MAT_WOOD;
	block_infos[BLK_LOG_OAK].slipperiness = 0.6;
	block_infos[BLK_LOG_ACACIA_1].hardness = 2.0;
	block_infos[BLK_LOG_ACACIA_1].material = MAT_WOOD;
	block_infos[BLK_LOG_ACACIA_1].slipperiness = 0.6;
	block_infos[BLK_LEAVES_OAK].hardness = 0.2;
	block_infos[BLK_LEAVES_OAK].material = MAT_LEAVES;
	block_infos[BLK_LEAVES_OAK].slipperiness = 0.6;
	block_infos[BLK_LEAVES_ACACIA].hardness = 0.2;
	block_infos[BLK_LEAVES_ACACIA].material = MAT_LEAVES;
	block_infos[BLK_LEAVES_ACACIA].slipperiness = 0.6;
	block_infos[BLK_SPONGE_DRY].hardness = 0.6;
	block_infos[BLK_SPONGE_DRY].material = MAT_SPONGE;
	block_infos[BLK_SPONGE_DRY].slipperiness = 0.6;
	block_infos[BLK_GLASS].hardness = 0.3;
	block_infos[BLK_GLASS].material = MAT_GLASS;
	block_infos[BLK_GLASS].slipperiness = 0.6;
	block_infos[BLK_ORELAPIS].hardness = 3.0;
	block_infos[BLK_ORELAPIS].material = MAT_ROCK;
	block_infos[BLK_ORELAPIS].slipperiness = 0.6;
	block_infos[BLK_BLOCKLAPIS].hardness = 3.0;
	block_infos[BLK_BLOCKLAPIS].material = MAT_IRON;
	block_infos[BLK_BLOCKLAPIS].slipperiness = 0.6;
	block_infos[BLK_DISPENSER].hardness = 3.5;
	block_infos[BLK_DISPENSER].material = MAT_ROCK;
	block_infos[BLK_DISPENSER].slipperiness = 0.6;
	block_infos[BLK_SANDSTONE].hardness = 0.8;
	block_infos[BLK_SANDSTONE].material = MAT_ROCK;
	block_infos[BLK_SANDSTONE].slipperiness = 0.6;
	block_infos[BLK_MUSICBLOCK].hardness = 0.8;
	block_infos[BLK_MUSICBLOCK].material = MAT_WOOD;
	block_infos[BLK_MUSICBLOCK].slipperiness = 0.6;
	block_infos[BLK_GOLDENRAIL].hardness = 0.7;
	block_infos[BLK_GOLDENRAIL].material = MAT_CIRCUITS;
	block_infos[BLK_GOLDENRAIL].slipperiness = 0.6;
	block_infos[BLK_DETECTORRAIL].hardness = 0.7;
	block_infos[BLK_DETECTORRAIL].material = MAT_CIRCUITS;
	block_infos[BLK_DETECTORRAIL].slipperiness = 0.6;
	block_infos[BLK_PISTONSTICKYBASE].hardness = 0.5;
	block_infos[BLK_PISTONSTICKYBASE].material = MAT_PISTON;
	block_infos[BLK_PISTONSTICKYBASE].slipperiness = 0.6;
	block_infos[BLK_WEB].hardness = 4.0;
	block_infos[BLK_WEB].material = MAT_WEB;
	block_infos[BLK_WEB].slipperiness = 0.6;
	block_infos[BLK_TALLGRASS_SHRUB].hardness = 0.0;
	block_infos[BLK_TALLGRASS_SHRUB].material = MAT_VINE;
	block_infos[BLK_TALLGRASS_SHRUB].slipperiness = 0.6;
	block_infos[BLK_DEADBUSH].hardness = 0.0;
	block_infos[BLK_DEADBUSH].material = MAT_VINE;
	block_infos[BLK_DEADBUSH].slipperiness = 0.6;
	block_infos[BLK_PISTONBASE].hardness = 0.5;
	block_infos[BLK_PISTONBASE].material = MAT_PISTON;
	block_infos[BLK_PISTONBASE].slipperiness = 0.6;
	block_infos[BLK_CLOTH_WHITE].hardness = 0.8;
	block_infos[BLK_CLOTH_WHITE].material = MAT_CLOTH;
	block_infos[BLK_CLOTH_WHITE].slipperiness = 0.6;
	block_infos[BLK_FLOWER1_DANDELION].hardness = 0.0;
	block_infos[BLK_FLOWER1_DANDELION].material = MAT_PLANTS;
	block_infos[BLK_FLOWER1_DANDELION].slipperiness = 0.6;
	block_infos[BLK_FLOWER2_POPPY].hardness = 0.0;
	block_infos[BLK_FLOWER2_POPPY].material = MAT_PLANTS;
	block_infos[BLK_FLOWER2_POPPY].slipperiness = 0.6;
	block_infos[BLK_MUSHROOM].hardness = 0.0;
	block_infos[BLK_MUSHROOM].material = MAT_PLANTS;
	block_infos[BLK_MUSHROOM].slipperiness = 0.6;
	block_infos[BLK_MUSHROOM_1].hardness = 0.0;
	block_infos[BLK_MUSHROOM_1].material = MAT_PLANTS;
	block_infos[BLK_MUSHROOM_1].slipperiness = 0.6;
	block_infos[BLK_BLOCKGOLD].hardness = 3.0;
	block_infos[BLK_BLOCKGOLD].material = MAT_IRON;
	block_infos[BLK_BLOCKGOLD].slipperiness = 0.6;
	block_infos[BLK_BLOCKIRON].hardness = 5.0;
	block_infos[BLK_BLOCKIRON].material = MAT_IRON;
	block_infos[BLK_BLOCKIRON].slipperiness = 0.6;
	block_infos[BLK_STONESLAB_STONE].hardness = 2.0;
	block_infos[BLK_STONESLAB_STONE].material = MAT_ROCK;
	block_infos[BLK_STONESLAB_STONE].slipperiness = 0.6;
	block_infos[BLK_BRICK].hardness = 2.0;
	block_infos[BLK_BRICK].material = MAT_ROCK;
	block_infos[BLK_BRICK].slipperiness = 0.6;
	block_infos[BLK_TNT].hardness = 0.0;
	block_infos[BLK_TNT].material = MAT_TNT;
	block_infos[BLK_TNT].slipperiness = 0.6;
	block_infos[BLK_BOOKSHELF].hardness = 1.5;
	block_infos[BLK_BOOKSHELF].material = MAT_WOOD;
	block_infos[BLK_BOOKSHELF].slipperiness = 0.6;
	block_infos[BLK_STONEMOSS].hardness = 2.0;
	block_infos[BLK_STONEMOSS].material = MAT_ROCK;
	block_infos[BLK_STONEMOSS].slipperiness = 0.6;
	block_infos[BLK_OBSIDIAN].hardness = 50.0;
	block_infos[BLK_OBSIDIAN].material = MAT_ROCK;
	block_infos[BLK_OBSIDIAN].slipperiness = 0.6;
	block_infos[BLK_TORCH].hardness = 0.0;
	block_infos[BLK_TORCH].material = MAT_CIRCUITS;
	block_infos[BLK_TORCH].slipperiness = 0.6;
	block_infos[BLK_ENDROD].hardness = 0.0;
	block_infos[BLK_ENDROD].material = MAT_CIRCUITS;
	block_infos[BLK_ENDROD].slipperiness = 0.6;
	block_infos[BLK_CHORUSPLANT].hardness = 0.4;
	block_infos[BLK_CHORUSPLANT].material = MAT_PLANTS;
	block_infos[BLK_CHORUSPLANT].slipperiness = 0.6;
	block_infos[BLK_CHORUSFLOWER].hardness = 0.4;
	block_infos[BLK_CHORUSFLOWER].material = MAT_PLANTS;
	block_infos[BLK_CHORUSFLOWER].slipperiness = 0.6;
	block_infos[BLK_PURPURBLOCK].hardness = 1.5;
	block_infos[BLK_PURPURBLOCK].material = MAT_ROCK;
	block_infos[BLK_PURPURBLOCK].slipperiness = 0.6;
	block_infos[BLK_PURPURPILLAR].hardness = 1.5;
	block_infos[BLK_PURPURPILLAR].material = MAT_ROCK;
	block_infos[BLK_PURPURPILLAR].slipperiness = 0.6;
	block_infos[BLK_STAIRSPURPUR].hardness = 1.5;
	block_infos[BLK_STAIRSPURPUR].material = MAT_ROCK;
	block_infos[BLK_STAIRSPURPUR].slipperiness = 0.6;
	block_infos[BLK_PURPURSLAB].hardness = 2.0;
	block_infos[BLK_PURPURSLAB].material = MAT_ROCK;
	block_infos[BLK_PURPURSLAB].slipperiness = 0.6;
	block_infos[BLK_MOBSPAWNER].hardness = 5.0;
	block_infos[BLK_MOBSPAWNER].material = MAT_ROCK;
	block_infos[BLK_MOBSPAWNER].slipperiness = 0.6;
	block_infos[BLK_STAIRSWOOD].hardness = 2.0;
	block_infos[BLK_STAIRSWOOD].material = MAT_WOOD;
	block_infos[BLK_STAIRSWOOD].slipperiness = 0.6;
	block_infos[BLK_CHEST].hardness = 2.5;
	block_infos[BLK_CHEST].material = MAT_WOOD;
	block_infos[BLK_CHEST].slipperiness = 0.6;
//
	block_infos[BLK_CHEST].onBlockInteract = &onBlockInteract_chest;
	block_infos[BLK_CHEST].onBlockDestroyed = &onBlockDestroyed_chest;
//
	block_infos[BLK_OREDIAMOND].hardness = 3.0;
	block_infos[BLK_OREDIAMOND].material = MAT_ROCK;
	block_infos[BLK_OREDIAMOND].slipperiness = 0.6;
	block_infos[BLK_BLOCKDIAMOND].hardness = 5.0;
	block_infos[BLK_BLOCKDIAMOND].material = MAT_IRON;
	block_infos[BLK_BLOCKDIAMOND].slipperiness = 0.6;
	block_infos[BLK_WORKBENCH].hardness = 2.5;
	block_infos[BLK_WORKBENCH].material = MAT_WOOD;
	block_infos[BLK_WORKBENCH].slipperiness = 0.6;
//
	block_infos[BLK_WORKBENCH].onBlockInteract = &onBlockInteract_workbench;
//
	block_infos[BLK_FARMLAND].hardness = 0.6;
	block_infos[BLK_FARMLAND].material = MAT_GROUND;
	block_infos[BLK_FARMLAND].slipperiness = 0.6;
	block_infos[BLK_FURNACE].hardness = 3.5;
	block_infos[BLK_FURNACE].material = MAT_ROCK;
	block_infos[BLK_FURNACE].slipperiness = 0.6;
//end auto
	block_infos[BLK_FURNACE].onBlockInteract = &onBlockInteract_furnace;
	block_infos[BLK_FURNACE].onBlockDestroyed = &onBlockDestroyed_furnace;
//begin auto
	block_infos[BLK_LADDER].hardness = 0.4;
	block_infos[BLK_LADDER].material = MAT_CIRCUITS;
	block_infos[BLK_LADDER].slipperiness = 0.6;
	block_infos[BLK_RAIL].hardness = 0.7;
	block_infos[BLK_RAIL].material = MAT_CIRCUITS;
	block_infos[BLK_RAIL].slipperiness = 0.6;
	block_infos[BLK_STAIRSSTONE].hardness = 2.0;
	block_infos[BLK_STAIRSSTONE].material = MAT_ROCK;
	block_infos[BLK_STAIRSSTONE].slipperiness = 0.6;
	block_infos[BLK_LEVER].hardness = 0.5;
	block_infos[BLK_LEVER].material = MAT_CIRCUITS;
	block_infos[BLK_LEVER].slipperiness = 0.6;
	block_infos[BLK_PRESSUREPLATESTONE].hardness = 0.5;
	block_infos[BLK_PRESSUREPLATESTONE].material = MAT_ROCK;
	block_infos[BLK_PRESSUREPLATESTONE].slipperiness = 0.6;
	block_infos[BLK_PRESSUREPLATEWOOD].hardness = 0.5;
	block_infos[BLK_PRESSUREPLATEWOOD].material = MAT_WOOD;
	block_infos[BLK_PRESSUREPLATEWOOD].slipperiness = 0.6;
	block_infos[BLK_OREREDSTONE].hardness = 3.0;
	block_infos[BLK_OREREDSTONE].material = MAT_ROCK;
	block_infos[BLK_OREREDSTONE].slipperiness = 0.6;
	block_infos[BLK_NOTGATE].hardness = 0.0;
	block_infos[BLK_NOTGATE].material = MAT_CIRCUITS;
	block_infos[BLK_NOTGATE].slipperiness = 0.6;
	block_infos[BLK_BUTTON].hardness = 0.5;
	block_infos[BLK_BUTTON].material = MAT_CIRCUITS;
	block_infos[BLK_BUTTON].slipperiness = 0.6;
	block_infos[BLK_SNOW].hardness = 0.1;
	block_infos[BLK_SNOW].material = MAT_SNOW;
	block_infos[BLK_SNOW].slipperiness = 0.6;
	block_infos[BLK_ICE].hardness = 0.5;
	block_infos[BLK_ICE].material = MAT_ICE;
	block_infos[BLK_ICE].slipperiness = 0.98;
	block_infos[BLK_SNOW_15].hardness = 0.2;
	block_infos[BLK_SNOW_15].material = MAT_CRAFTED_SNOW;
	block_infos[BLK_SNOW_15].slipperiness = 0.6;
	block_infos[BLK_CACTUS].hardness = 0.4;
	block_infos[BLK_CACTUS].material = MAT_CACTUS;
	block_infos[BLK_CACTUS].slipperiness = 0.6;
	block_infos[BLK_CLAY].hardness = 0.6;
	block_infos[BLK_CLAY].material = MAT_CLAY;
	block_infos[BLK_CLAY].slipperiness = 0.6;
	block_infos[BLK_JUKEBOX].hardness = 2.0;
	block_infos[BLK_JUKEBOX].material = MAT_WOOD;
	block_infos[BLK_JUKEBOX].slipperiness = 0.6;
	block_infos[BLK_FENCE].hardness = 2.0;
	block_infos[BLK_FENCE].material = MAT_WOOD;
	block_infos[BLK_FENCE].slipperiness = 0.6;
	block_infos[BLK_SPRUCEFENCE].hardness = 2.0;
	block_infos[BLK_SPRUCEFENCE].material = MAT_WOOD;
	block_infos[BLK_SPRUCEFENCE].slipperiness = 0.6;
	block_infos[BLK_BIRCHFENCE].hardness = 2.0;
	block_infos[BLK_BIRCHFENCE].material = MAT_WOOD;
	block_infos[BLK_BIRCHFENCE].slipperiness = 0.6;
	block_infos[BLK_JUNGLEFENCE].hardness = 2.0;
	block_infos[BLK_JUNGLEFENCE].material = MAT_WOOD;
	block_infos[BLK_JUNGLEFENCE].slipperiness = 0.6;
	block_infos[BLK_DARKOAKFENCE].hardness = 2.0;
	block_infos[BLK_DARKOAKFENCE].material = MAT_WOOD;
	block_infos[BLK_DARKOAKFENCE].slipperiness = 0.6;
	block_infos[BLK_ACACIAFENCE].hardness = 2.0;
	block_infos[BLK_ACACIAFENCE].material = MAT_WOOD;
	block_infos[BLK_ACACIAFENCE].slipperiness = 0.6;
	block_infos[BLK_PUMPKIN].hardness = 1.0;
	block_infos[BLK_PUMPKIN].material = MAT_GOURD;
	block_infos[BLK_PUMPKIN].slipperiness = 0.6;
	block_infos[BLK_HELLROCK].hardness = 0.4;
	block_infos[BLK_HELLROCK].material = MAT_ROCK;
	block_infos[BLK_HELLROCK].slipperiness = 0.6;
	block_infos[BLK_HELLSAND].hardness = 0.5;
	block_infos[BLK_HELLSAND].material = MAT_SAND;
	block_infos[BLK_HELLSAND].slipperiness = 0.6;
	block_infos[BLK_LIGHTGEM].hardness = 0.3;
	block_infos[BLK_LIGHTGEM].material = MAT_GLASS;
	block_infos[BLK_LIGHTGEM].slipperiness = 0.6;
	block_infos[BLK_LITPUMPKIN].hardness = 1.0;
	block_infos[BLK_LITPUMPKIN].material = MAT_GOURD;
	block_infos[BLK_LITPUMPKIN].slipperiness = 0.6;
	block_infos[BLK_TRAPDOOR].hardness = 3.0;
	block_infos[BLK_TRAPDOOR].material = MAT_WOOD;
	block_infos[BLK_TRAPDOOR].slipperiness = 0.6;
	block_infos[BLK_MONSTERSTONEEGG_STONE].hardness = 0.75;
	block_infos[BLK_MONSTERSTONEEGG_STONE].material = MAT_CLAY;
	block_infos[BLK_MONSTERSTONEEGG_STONE].slipperiness = 0.6;
	block_infos[BLK_STONEBRICKSMOOTH].hardness = 1.5;
	block_infos[BLK_STONEBRICKSMOOTH].material = MAT_ROCK;
	block_infos[BLK_STONEBRICKSMOOTH].slipperiness = 0.6;
	block_infos[BLK_MUSHROOM_2].hardness = 0.2;
	block_infos[BLK_MUSHROOM_2].material = MAT_WOOD;
	block_infos[BLK_MUSHROOM_2].slipperiness = 0.6;
	block_infos[BLK_MUSHROOM_17].hardness = 0.2;
	block_infos[BLK_MUSHROOM_17].material = MAT_WOOD;
	block_infos[BLK_MUSHROOM_17].slipperiness = 0.6;
	block_infos[BLK_FENCEIRON].hardness = 5.0;
	block_infos[BLK_FENCEIRON].material = MAT_IRON;
	block_infos[BLK_FENCEIRON].slipperiness = 0.6;
	block_infos[BLK_THINGLASS].hardness = 0.3;
	block_infos[BLK_THINGLASS].material = MAT_GLASS;
	block_infos[BLK_THINGLASS].slipperiness = 0.6;
	block_infos[BLK_MELON].hardness = 1.0;
	block_infos[BLK_MELON].material = MAT_GOURD;
	block_infos[BLK_MELON].slipperiness = 0.6;
	block_infos[BLK_VINE].hardness = 0.2;
	block_infos[BLK_VINE].material = MAT_VINE;
	block_infos[BLK_VINE].slipperiness = 0.6;
	block_infos[BLK_FENCEGATE].hardness = 2.0;
	block_infos[BLK_FENCEGATE].material = MAT_WOOD;
	block_infos[BLK_FENCEGATE].slipperiness = 0.6;
	block_infos[BLK_SPRUCEFENCEGATE].hardness = 2.0;
	block_infos[BLK_SPRUCEFENCEGATE].material = MAT_WOOD;
	block_infos[BLK_SPRUCEFENCEGATE].slipperiness = 0.6;
	block_infos[BLK_BIRCHFENCEGATE].hardness = 2.0;
	block_infos[BLK_BIRCHFENCEGATE].material = MAT_WOOD;
	block_infos[BLK_BIRCHFENCEGATE].slipperiness = 0.6;
	block_infos[BLK_JUNGLEFENCEGATE].hardness = 2.0;
	block_infos[BLK_JUNGLEFENCEGATE].material = MAT_WOOD;
	block_infos[BLK_JUNGLEFENCEGATE].slipperiness = 0.6;
	block_infos[BLK_DARKOAKFENCEGATE].hardness = 2.0;
	block_infos[BLK_DARKOAKFENCEGATE].material = MAT_WOOD;
	block_infos[BLK_DARKOAKFENCEGATE].slipperiness = 0.6;
	block_infos[BLK_ACACIAFENCEGATE].hardness = 2.0;
	block_infos[BLK_ACACIAFENCEGATE].material = MAT_WOOD;
	block_infos[BLK_ACACIAFENCEGATE].slipperiness = 0.6;
	block_infos[BLK_STAIRSBRICK].hardness = 2.0;
	block_infos[BLK_STAIRSBRICK].material = MAT_ROCK;
	block_infos[BLK_STAIRSBRICK].slipperiness = 0.6;
	block_infos[BLK_STAIRSSTONEBRICKSMOOTH].hardness = 1.5;
	block_infos[BLK_STAIRSSTONEBRICKSMOOTH].material = MAT_ROCK;
	block_infos[BLK_STAIRSSTONEBRICKSMOOTH].slipperiness = 0.6;
	block_infos[BLK_MYCEL].hardness = 0.6;
	block_infos[BLK_MYCEL].material = MAT_GRASS;
	block_infos[BLK_MYCEL].slipperiness = 0.6;
	block_infos[BLK_WATERLILY].hardness = 0.0;
	block_infos[BLK_WATERLILY].material = MAT_PLANTS;
	block_infos[BLK_WATERLILY].slipperiness = 0.6;
	block_infos[BLK_NETHERBRICK].hardness = 2.0;
	block_infos[BLK_NETHERBRICK].material = MAT_ROCK;
	block_infos[BLK_NETHERBRICK].slipperiness = 0.6;
	block_infos[BLK_NETHERFENCE].hardness = 2.0;
	block_infos[BLK_NETHERFENCE].material = MAT_ROCK;
	block_infos[BLK_NETHERFENCE].slipperiness = 0.6;
	block_infos[BLK_STAIRSNETHERBRICK].hardness = 2.0;
	block_infos[BLK_STAIRSNETHERBRICK].material = MAT_ROCK;
	block_infos[BLK_STAIRSNETHERBRICK].slipperiness = 0.6;
	block_infos[BLK_ENCHANTMENTTABLE].hardness = 5.0;
	block_infos[BLK_ENCHANTMENTTABLE].material = MAT_ROCK;
	block_infos[BLK_ENCHANTMENTTABLE].slipperiness = 0.6;
	block_infos[BLK_ENDPORTALFRAME].hardness = -1.0;
	block_infos[BLK_ENDPORTALFRAME].material = MAT_ROCK;
	block_infos[BLK_ENDPORTALFRAME].slipperiness = 0.6;
	block_infos[BLK_WHITESTONE].hardness = 3.0;
	block_infos[BLK_WHITESTONE].material = MAT_ROCK;
	block_infos[BLK_WHITESTONE].slipperiness = 0.6;
	block_infos[BLK_ENDBRICKS].hardness = 0.8;
	block_infos[BLK_ENDBRICKS].material = MAT_ROCK;
	block_infos[BLK_ENDBRICKS].slipperiness = 0.6;
	block_infos[BLK_DRAGONEGG].hardness = 3.0;
	block_infos[BLK_DRAGONEGG].material = MAT_DRAGON_EGG;
	block_infos[BLK_DRAGONEGG].slipperiness = 0.6;
	block_infos[BLK_REDSTONELIGHT].hardness = 0.3;
	block_infos[BLK_REDSTONELIGHT].material = MAT_REDSTONE_LIGHT;
	block_infos[BLK_REDSTONELIGHT].slipperiness = 0.6;
	block_infos[BLK_WOODSLAB_OAK].hardness = 2.0;
	block_infos[BLK_WOODSLAB_OAK].material = MAT_WOOD;
	block_infos[BLK_WOODSLAB_OAK].slipperiness = 0.6;
	block_infos[BLK_STAIRSSANDSTONE].hardness = 0.8;
	block_infos[BLK_STAIRSSANDSTONE].material = MAT_ROCK;
	block_infos[BLK_STAIRSSANDSTONE].slipperiness = 0.6;
	block_infos[BLK_OREEMERALD].hardness = 3.0;
	block_infos[BLK_OREEMERALD].material = MAT_ROCK;
	block_infos[BLK_OREEMERALD].slipperiness = 0.6;
	block_infos[BLK_ENDERCHEST].hardness = 22.5;
	block_infos[BLK_ENDERCHEST].material = MAT_ROCK;
	block_infos[BLK_ENDERCHEST].slipperiness = 0.6;
	block_infos[BLK_TRIPWIRESOURCE].hardness = 0.0;
	block_infos[BLK_TRIPWIRESOURCE].material = MAT_CIRCUITS;
	block_infos[BLK_TRIPWIRESOURCE].slipperiness = 0.6;
	block_infos[BLK_BLOCKEMERALD].hardness = 5.0;
	block_infos[BLK_BLOCKEMERALD].material = MAT_IRON;
	block_infos[BLK_BLOCKEMERALD].slipperiness = 0.6;
	block_infos[BLK_STAIRSWOODSPRUCE].hardness = 2.0;
	block_infos[BLK_STAIRSWOODSPRUCE].material = MAT_WOOD;
	block_infos[BLK_STAIRSWOODSPRUCE].slipperiness = 0.6;
	block_infos[BLK_STAIRSWOODBIRCH].hardness = 2.0;
	block_infos[BLK_STAIRSWOODBIRCH].material = MAT_WOOD;
	block_infos[BLK_STAIRSWOODBIRCH].slipperiness = 0.6;
	block_infos[BLK_STAIRSWOODJUNGLE].hardness = 2.0;
	block_infos[BLK_STAIRSWOODJUNGLE].material = MAT_WOOD;
	block_infos[BLK_STAIRSWOODJUNGLE].slipperiness = 0.6;
	block_infos[BLK_COMMANDBLOCK].hardness = -1.0;
	block_infos[BLK_COMMANDBLOCK].material = MAT_IRON;
	block_infos[BLK_COMMANDBLOCK].slipperiness = 0.6;
	block_infos[BLK_BEACON].hardness = 3.0;
	block_infos[BLK_BEACON].material = MAT_GLASS;
	block_infos[BLK_BEACON].slipperiness = 0.6;
	block_infos[BLK_COBBLEWALL_NORMAL].hardness = 2.0;
	block_infos[BLK_COBBLEWALL_NORMAL].material = MAT_ROCK;
	block_infos[BLK_COBBLEWALL_NORMAL].slipperiness = 0.6;
	block_infos[BLK_BUTTON_15].hardness = 0.5;
	block_infos[BLK_BUTTON_15].material = MAT_CIRCUITS;
	block_infos[BLK_BUTTON_15].slipperiness = 0.6;
	block_infos[BLK_ANVIL_INTACT].hardness = 5.0;
	block_infos[BLK_ANVIL_INTACT].material = MAT_ANVIL;
	block_infos[BLK_ANVIL_INTACT].slipperiness = 0.6;
	block_infos[BLK_CHESTTRAP].hardness = 2.5;
	block_infos[BLK_CHESTTRAP].material = MAT_WOOD;
	block_infos[BLK_CHESTTRAP].slipperiness = 0.6;
//
	block_infos[BLK_CHESTTRAP].onBlockInteract = &onBlockInteract_chest;
//
	block_infos[BLK_WEIGHTEDPLATE_LIGHT].hardness = 0.5;
	block_infos[BLK_WEIGHTEDPLATE_LIGHT].material = MAT_IRON;
	block_infos[BLK_WEIGHTEDPLATE_LIGHT].slipperiness = 0.6;
	block_infos[BLK_WEIGHTEDPLATE_HEAVY].hardness = 0.5;
	block_infos[BLK_WEIGHTEDPLATE_HEAVY].material = MAT_IRON;
	block_infos[BLK_WEIGHTEDPLATE_HEAVY].slipperiness = 0.6;
	block_infos[BLK_DAYLIGHTDETECTOR].hardness = 0.2;
	block_infos[BLK_DAYLIGHTDETECTOR].material = MAT_WOOD;
	block_infos[BLK_DAYLIGHTDETECTOR].slipperiness = 0.6;
	block_infos[BLK_BLOCKREDSTONE].hardness = 5.0;
	block_infos[BLK_BLOCKREDSTONE].material = MAT_IRON;
	block_infos[BLK_BLOCKREDSTONE].slipperiness = 0.6;
	block_infos[BLK_NETHERQUARTZ].hardness = 3.0;
	block_infos[BLK_NETHERQUARTZ].material = MAT_ROCK;
	block_infos[BLK_NETHERQUARTZ].slipperiness = 0.6;
	block_infos[BLK_HOPPER].hardness = 3.0;
	block_infos[BLK_HOPPER].material = MAT_IRON;
	block_infos[BLK_HOPPER].slipperiness = 0.6;
	block_infos[BLK_QUARTZBLOCK].hardness = 0.8;
	block_infos[BLK_QUARTZBLOCK].material = MAT_ROCK;
	block_infos[BLK_QUARTZBLOCK].slipperiness = 0.6;
	block_infos[BLK_STAIRSQUARTZ].hardness = 0.8;
	block_infos[BLK_STAIRSQUARTZ].material = MAT_ROCK;
	block_infos[BLK_STAIRSQUARTZ].slipperiness = 0.6;
	block_infos[BLK_ACTIVATORRAIL].hardness = 0.7;
	block_infos[BLK_ACTIVATORRAIL].material = MAT_CIRCUITS;
	block_infos[BLK_ACTIVATORRAIL].slipperiness = 0.6;
	block_infos[BLK_DROPPER].hardness = 3.5;
	block_infos[BLK_DROPPER].material = MAT_ROCK;
	block_infos[BLK_DROPPER].slipperiness = 0.6;
	block_infos[BLK_CLAYHARDENEDSTAINED_WHITE].hardness = 1.25;
	block_infos[BLK_CLAYHARDENEDSTAINED_WHITE].material = MAT_ROCK;
	block_infos[BLK_CLAYHARDENEDSTAINED_WHITE].slipperiness = 0.6;
	block_infos[BLK_BARRIER].hardness = -1.0;
	block_infos[BLK_BARRIER].material = MAT_BARRIER;
	block_infos[BLK_BARRIER].slipperiness = 0.6;
	block_infos[BLK_IRONTRAPDOOR].hardness = 5.0;
	block_infos[BLK_IRONTRAPDOOR].material = MAT_IRON;
	block_infos[BLK_IRONTRAPDOOR].slipperiness = 0.6;
	block_infos[BLK_HAYBLOCK].hardness = 0.5;
	block_infos[BLK_HAYBLOCK].material = MAT_GRASS;
	block_infos[BLK_HAYBLOCK].slipperiness = 0.6;
	block_infos[BLK_WOOLCARPET_WHITE].hardness = 0.1;
	block_infos[BLK_WOOLCARPET_WHITE].material = MAT_CARPET;
	block_infos[BLK_WOOLCARPET_WHITE].slipperiness = 0.6;
	block_infos[BLK_CLAYHARDENED].hardness = 1.25;
	block_infos[BLK_CLAYHARDENED].material = MAT_ROCK;
	block_infos[BLK_CLAYHARDENED].slipperiness = 0.6;
	block_infos[BLK_BLOCKCOAL].hardness = 5.0;
	block_infos[BLK_BLOCKCOAL].material = MAT_ROCK;
	block_infos[BLK_BLOCKCOAL].slipperiness = 0.6;
	block_infos[BLK_ICEPACKED].hardness = 0.5;
	block_infos[BLK_ICEPACKED].material = MAT_PACKED_ICE;
	block_infos[BLK_ICEPACKED].slipperiness = 0.98;
	block_infos[BLK_STAIRSWOODACACIA].hardness = 2.0;
	block_infos[BLK_STAIRSWOODACACIA].material = MAT_WOOD;
	block_infos[BLK_STAIRSWOODACACIA].slipperiness = 0.6;
	block_infos[BLK_STAIRSWOODDARKOAK].hardness = 2.0;
	block_infos[BLK_STAIRSWOODDARKOAK].material = MAT_WOOD;
	block_infos[BLK_STAIRSWOODDARKOAK].slipperiness = 0.6;
	block_infos[BLK_SLIME].hardness = 0.0;
	block_infos[BLK_SLIME].material = MAT_CLAY;
	block_infos[BLK_SLIME].slipperiness = 0.8;
	block_infos[BLK_GRASSPATH].hardness = 0.65;
	block_infos[BLK_GRASSPATH].material = MAT_GROUND;
	block_infos[BLK_GRASSPATH].slipperiness = 0.6;
	block_infos[BLK_DOUBLEPLANT_SUNFLOWER].hardness = 0.0;
	block_infos[BLK_DOUBLEPLANT_SUNFLOWER].material = MAT_VINE;
	block_infos[BLK_DOUBLEPLANT_SUNFLOWER].slipperiness = 0.6;
	block_infos[BLK_STAINEDGLASS_WHITE].hardness = 0.3;
	block_infos[BLK_STAINEDGLASS_WHITE].material = MAT_GLASS;
	block_infos[BLK_STAINEDGLASS_WHITE].slipperiness = 0.6;
	block_infos[BLK_THINSTAINEDGLASS_WHITE].hardness = 0.3;
	block_infos[BLK_THINSTAINEDGLASS_WHITE].material = MAT_GLASS;
	block_infos[BLK_THINSTAINEDGLASS_WHITE].slipperiness = 0.6;
	block_infos[BLK_PRISMARINE_ROUGH].hardness = 1.5;
	block_infos[BLK_PRISMARINE_ROUGH].material = MAT_ROCK;
	block_infos[BLK_PRISMARINE_ROUGH].slipperiness = 0.6;
	block_infos[BLK_SEALANTERN].hardness = 0.3;
	block_infos[BLK_SEALANTERN].material = MAT_GLASS;
	block_infos[BLK_SEALANTERN].slipperiness = 0.6;
	block_infos[BLK_REDSANDSTONE].hardness = 0.8;
	block_infos[BLK_REDSANDSTONE].material = MAT_ROCK;
	block_infos[BLK_REDSANDSTONE].slipperiness = 0.6;
	block_infos[BLK_STAIRSREDSANDSTONE].hardness = 0.8;
	block_infos[BLK_STAIRSREDSANDSTONE].material = MAT_ROCK;
	block_infos[BLK_STAIRSREDSANDSTONE].slipperiness = 0.6;
	block_infos[BLK_STONESLAB2_RED_SANDSTONE].hardness = 2.0;
	block_infos[BLK_STONESLAB2_RED_SANDSTONE].material = MAT_ROCK;
	block_infos[BLK_STONESLAB2_RED_SANDSTONE].slipperiness = 0.6;
	block_infos[BLK_REPEATINGCOMMANDBLOCK].hardness = -1.0;
	block_infos[BLK_REPEATINGCOMMANDBLOCK].material = MAT_IRON;
	block_infos[BLK_REPEATINGCOMMANDBLOCK].slipperiness = 0.6;
	block_infos[BLK_CHAINCOMMANDBLOCK].hardness = -1.0;
	block_infos[BLK_CHAINCOMMANDBLOCK].material = MAT_IRON;
	block_infos[BLK_CHAINCOMMANDBLOCK].slipperiness = 0.6;
	block_infos[BLK_MAGMA].hardness = 0.5;
	block_infos[BLK_MAGMA].material = MAT_ROCK;
	block_infos[BLK_MAGMA].slipperiness = 0.6;
	block_infos[BLK_NETHERWARTBLOCK].hardness = 1.0;
	block_infos[BLK_NETHERWARTBLOCK].material = MAT_GRASS;
	block_infos[BLK_NETHERWARTBLOCK].slipperiness = 0.6;
	block_infos[BLK_REDNETHERBRICK].hardness = 2.0;
	block_infos[BLK_REDNETHERBRICK].material = MAT_ROCK;
	block_infos[BLK_REDNETHERBRICK].slipperiness = 0.6;
	block_infos[BLK_BONEBLOCK].hardness = 2.0;
	block_infos[BLK_BONEBLOCK].material = MAT_ROCK;
	block_infos[BLK_BONEBLOCK].slipperiness = 0.6;
	block_infos[BLK_STRUCTUREVOID].hardness = 0.0;
	block_infos[BLK_STRUCTUREVOID].material = MAT_STRUCTURE_VOID;
	block_infos[BLK_STRUCTUREVOID].slipperiness = 0.6;
	block_infos[BLK_OBSERVER].hardness = 3.0;
	block_infos[BLK_OBSERVER].material = MAT_ROCK;
	block_infos[BLK_OBSERVER].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXWHITE].hardness = 2.0;
	block_infos[BLK_SHULKERBOXWHITE].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXWHITE].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXORANGE].hardness = 2.0;
	block_infos[BLK_SHULKERBOXORANGE].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXORANGE].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXMAGENTA].hardness = 2.0;
	block_infos[BLK_SHULKERBOXMAGENTA].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXMAGENTA].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXLIGHTBLUE].hardness = 2.0;
	block_infos[BLK_SHULKERBOXLIGHTBLUE].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXLIGHTBLUE].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXYELLOW].hardness = 2.0;
	block_infos[BLK_SHULKERBOXYELLOW].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXYELLOW].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXLIME].hardness = 2.0;
	block_infos[BLK_SHULKERBOXLIME].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXLIME].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXPINK].hardness = 2.0;
	block_infos[BLK_SHULKERBOXPINK].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXPINK].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXGRAY].hardness = 2.0;
	block_infos[BLK_SHULKERBOXGRAY].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXGRAY].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXSILVER].hardness = 2.0;
	block_infos[BLK_SHULKERBOXSILVER].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXSILVER].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXCYAN].hardness = 2.0;
	block_infos[BLK_SHULKERBOXCYAN].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXCYAN].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXPURPLE].hardness = 2.0;
	block_infos[BLK_SHULKERBOXPURPLE].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXPURPLE].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXBLUE].hardness = 2.0;
	block_infos[BLK_SHULKERBOXBLUE].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXBLUE].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXBROWN].hardness = 2.0;
	block_infos[BLK_SHULKERBOXBROWN].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXBROWN].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXGREEN].hardness = 2.0;
	block_infos[BLK_SHULKERBOXGREEN].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXGREEN].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXRED].hardness = 2.0;
	block_infos[BLK_SHULKERBOXRED].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXRED].slipperiness = 0.6;
	block_infos[BLK_SHULKERBOXBLACK].hardness = 2.0;
	block_infos[BLK_SHULKERBOXBLACK].material = MAT_ROCK;
	block_infos[BLK_SHULKERBOXBLACK].slipperiness = 0.6;
	block_infos[BLK_STRUCTUREBLOCK].hardness = -1.0;
	block_infos[BLK_STRUCTUREBLOCK].material = MAT_IRON;
	block_infos[BLK_STRUCTUREBLOCK].slipperiness = 0.6;
}
